--Copyright (C) 2021 Kritik Agarwal <https://github.com/Kritik007>
--------------------------------------------------------------------------------------------------------------------------------

------------------ START ----------------

-- CREATE DATABASE
CREATE DATABASE [SFDB];
GO

--USING THE CREATED/EXISTING DATABASE
USE [SFDB];
GO

--CREATING TABLES
--T1
CREATE TABLE [STUDENT] (
	[USN] VARCHAR(10) NOT NULL,
	[SNAME] VARCHAR(25) NOT NULL,
	[BRANCH] VARCHAR(10) NOT NULL,
	[SEM] INT NOT NULL, 
	[ADDRESS] VARCHAR(25) NOT NULL, 
	[PHONE] VARCHAR(10) NOT NULL,
	[COURSE_CODE] VARCHAR(10) NOT NULL, 
	[COURSE_NAME] VARCHAR(20) NOT NULL,
	PRIMARY KEY([USN],[SNAME])
);
GO

--T2
CREATE TABLE [FACULTY] (
	[FNAME] VARCHAR(20) NOT NULL, 
	[FID] VARCHAR(20) NOT NULL, 
	[BRANCH] VARCHAR(10) NOT NULL, 
	[COURSE_CODE] VARCHAR(10) NOT NULL, 
	[ADDRESS] VARCHAR(20) NOT NULL, 
	[PHONE] VARCHAR(20) NOT NULL,
	PRIMARY KEY([FNAME],[FID])
);
GO

--T3
CREATE TABLE [COURSE] (
	[COURSE_CODE] VARCHAR(10) NOT NULL, 
	[COURSE_NAME] VARCHAR(20) NOT NULL, 
	[FACULTY] VARCHAR(20) NOT NULL, 
	[BRANCH] VARCHAR(20) NOT NULL,
	PRIMARY KEY([COURSE_CODE],[COURSE_NAME])
);
GO

--T4
CREATE TABLE [MARKS] (
	[USN] VARCHAR(10) NOT NULL, 
	[SNAME] VARCHAR(20) NOT NULL, 
	[COURSE_CODE] VARCHAR(10) NOT NULL, 
	[COURSE_NAME] VARCHAR(20) NOT NULL, 
	[IAT-1] INT NOT NULL,
	[IAT-2] INT NOT NULL,
	[CCE] INT NOT NULL,
	[SEE] INT NOT NULL
);
GO

SELECT * FROM FACULTY, STUDENT, COURSE, MARKS;